---
# Runs on Wednesday after deps repo.
# Apply the "not ready" label to prevent cascaded CI runs on each auto-merge.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      wire:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"

  - package-ecosystem: "gomod"
    directory: "/tools"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      tools:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"
