---
# TODO https://github.com/FerretDB/wire/issues/4

version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - gochecksumtype
    - govet
    - staticcheck

  # https://golangci-lint.run/usage/linters/
  settings:
    # asciicheck
    gochecksumtype:
      default-signifies-exhaustive: true
      include-shared-interfaces: false
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    staticcheck:
      checks: [all]

  exclusions:
    generated: strict
    warn-unused: true
    rules:
      # that's a valid usage of bson.D / bson.E
      - linters: [govet]
        text: "\\Qcomposites: go.mongodb.org/mongo-driver/v2/bson.E struct literal uses unkeyed fields"

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      no-inline-comments: false
      no-prefix-comments: true
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/FerretDB/wire
    golines:
      max-len: 130

  exclusions:
    generated: strict
    warn-unused: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 1m
