---
linters:
  disable-all: true
  enable:
    # TODO https://github.com/FerretDB/wire/issues/4
    - asciicheck
    - gci
    - goimports
    - govet
    - staticcheck

# https://golangci-lint.run/usage/linters/
linters-settings:
  # asciicheck
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/FerretDB/wire)
    skip-generated: false
  goimports:
    local-prefixes: github.com/FerretDB/wire
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  staticcheck:
    checks: [all]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-use-default: false
  exclude-rules:
    # that's a valid usage of bson.D / bson.E
    - linters: [govet]
      text: "composites: go.mongodb.org/mongo-driver/v2/bson.E struct literal uses unkeyed fields"


run:
  timeout: 3m
