---
# TODO https://github.com/FerretDB/wire/issues/4

version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - govet
    - staticcheck

  # https://golangci-lint.run/usage/linters/
  settings:
    # asciicheck
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    staticcheck:
      checks: [all]

  exclusions:
    generated: strict
    warn-unused: true
    rules:
      # that's a valid usage of bson.D / bson.E
      - linters: [govet]
        text: "\\Qcomposites: go.mongodb.org/mongo-driver/v2/bson.E struct literal uses unkeyed fields"

formatters:
  enable:
    - gci
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/FerretDB/wire)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/FerretDB/wire

  exclusions:
    generated: strict
    warn-unused: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 1m
