// Code generated by "stringer -linecomment -output stringers.go -type decodeMode,tag,BinarySubtype"; DO NOT EDIT.

package wirebson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[decodeShallow-1]
	_ = x[decodeDeep-2]
}

const _decodeMode_name = "decodeShallowdecodeDeep"

var _decodeMode_index = [...]uint8{0, 13, 23}

func (i decodeMode) String() string {
	i -= 1
	if i < 0 || i >= decodeMode(len(_decodeMode_index)-1) {
		return "decodeMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _decodeMode_name[_decodeMode_index[i]:_decodeMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tagFloat64-1]
	_ = x[tagString-2]
	_ = x[tagDocument-3]
	_ = x[tagArray-4]
	_ = x[tagBinary-5]
	_ = x[tagUndefined-6]
	_ = x[tagObjectID-7]
	_ = x[tagBool-8]
	_ = x[tagTime-9]
	_ = x[tagNull-10]
	_ = x[tagRegex-11]
	_ = x[tagDBPointer-12]
	_ = x[tagJavaScript-13]
	_ = x[tagSymbol-14]
	_ = x[tagJavaScriptScope-15]
	_ = x[tagInt32-16]
	_ = x[tagTimestamp-17]
	_ = x[tagInt64-18]
	_ = x[tagDecimal128-19]
	_ = x[tagMinKey-255]
	_ = x[tagMaxKey-127]
}

const (
	_tag_name_0 = "Float64StringDocumentArrayBinaryUndefinedObjectIDBoolTimeNullRegexDBPointerJavaScriptSymbolJavaScriptScopeInt32TimestampInt64Decimal128"
	_tag_name_1 = "MaxKey"
	_tag_name_2 = "MinKey"
)

var (
	_tag_index_0 = [...]uint8{0, 7, 13, 21, 26, 32, 41, 49, 53, 57, 61, 66, 75, 85, 91, 106, 111, 120, 125, 135}
)

func (i tag) String() string {
	switch {
	case 1 <= i && i <= 19:
		i -= 1
		return _tag_name_0[_tag_index_0[i]:_tag_index_0[i+1]]
	case i == 127:
		return _tag_name_1
	case i == 255:
		return _tag_name_2
	default:
		return "tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinaryGeneric-0]
	_ = x[BinaryFunction-1]
	_ = x[BinaryGenericOld-2]
	_ = x[BinaryUUIDOld-3]
	_ = x[BinaryUUID-4]
	_ = x[BinaryMD5-5]
	_ = x[BinaryEncrypted-6]
	_ = x[BinaryCompressed-7]
	_ = x[BinarySensitive-8]
	_ = x[BinaryVector-9]
	_ = x[BinaryUser-128]
}

const (
	_BinarySubtype_name_0 = "genericfunctiongeneric-olduuid-olduuidmd5encryptedcompressedsensitivevector"
	_BinarySubtype_name_1 = "user"
)

var (
	_BinarySubtype_index_0 = [...]uint8{0, 7, 15, 26, 34, 38, 41, 50, 60, 69, 75}
)

func (i BinarySubtype) String() string {
	switch {
	case i <= 9:
		return _BinarySubtype_name_0[_BinarySubtype_index_0[i]:_BinarySubtype_index_0[i+1]]
	case i == 128:
		return _BinarySubtype_name_1
	default:
		return "BinarySubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
