---
# This file is used by integration tests.

services:
  database:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-mongo}.Dockerfile
    ports:
      - 27017:27017
    environment:
      # MongoDB
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

      # FerretDB v1
      FERRETDB_SETUP_USERNAME: username
      FERRETDB_SETUP_PASSWORD: password
      FERRETDB_SETUP_DATABASE: admin
      FERRETDB_TEST_ENABLE_NEW_AUTH: true

      # PostgreSQL for FerretDB v2
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
