---
name: Go
on:
  pull_request:
    types:
      - unlabeled # if GitHub Actions stuck, add and remove "not ready" label to force rebuild
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    - cron: "12 0 * * *"

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOLANGCI_LINT_CACHE: /home/runner/go/cache/lint
  GOMODCACHE: /home/runner/go/mod
  GOPROXY: https://proxy.golang.org
  GOTOOLCHAIN: local

  # TODO https://github.com/FerretDB/wire/issues/9
  GOEXPERIMENT: rangefunc

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    # Do not run this job in parallel for any PR change or branch push.
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'not ready')

    steps:
      # TODO https://github.com/FerretDB/github-actions/issues/211
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: FerretDB/github-actions/setup-go@main
        with:
          cache-key: test

      - name: Install Task and tools
        run: go generate -x
        working-directory: tools

      - name: Init
        run: bin/task init

      - name: Generate and format
        run: bin/task gen

      - name: Run tests
        run: bin/task test

      - name: Fuzz
        run: bin/task fuzz

      - name: Check dirty
        run: |
          git status
          git diff --exit-code
